degree of freedom rename
capitalone/DataProfiler pull request #1056
Opened 2023-10-27 03:45 UTC by mainkhan

2023-10-27 03:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/capitalone/DataProfiler?pullRequest=1056) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/capitalone/DataProfiler?pullRequest=1056) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: taylorfturner<br/>:x: mainkhan<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/capitalone/DataProfiler?pullRequest=1056) it.</sub>

2023-10-27 12:49 UTC, taylorfturner commented
@mainkhan if you don't mind, let's open this PR into `dev` and not `main`. Thanks for the contribution!

2023-10-27 12:50 UTC, taylorfturner requested changes
open PR into `dev`

2023-10-27 13:32 UTC, mainkhan commented
Hey @taylorfturner I changed the base branch. Sorry about that, I know it should be obvious but I think I got confused because in CONTRIBUTING.md the first step to create a pull request is to create a feature branch off of `main`

2023-10-27 13:45 UTC, taylorfturner commented
> Hey @taylorfturner I changed the base branch. Sorry about that, I know it should be obvious but I think I got confused because in CONTRIBUTING.md the first step to create a pull request is to create a feature branch off of `main`

Totally understandable -- we will update that for clarity. Poor direction on our part. Thanks for the contribution!

2023-10-27 16:57 UTC, taylorfturner commented on dataprofiler/tests/profilers/test_categorical_column_profile.py
since this is changing behavior of the output for end users
- we will need to be very clear in our communication about what changed and when (in PR notes)
- also will need to ensure documentation is updated properly to ensure that is up to date and matching code's current state with this change

2023-10-27 16:59 UTC, taylorfturner commented on dataprofiler/tests/profilers/test_categorical_column_profile.py
@mainkhan my one thought is that we should 
- research needed documentation changes [here](https://capitalone.github.io/DataProfiler/docs/0.10.5/html/index.html)
- if any needed changes open up a PR into `dev-gh-pages` in parallel to the code change

2023-10-27 18:28 UTC, mainkhan commented on dataprofiler/tests/profilers/test_categorical_column_profile.py
I looked in to the docs and could not find any information documenting explicitly what the output will be so I'm not sure we need to change any existing documentation. Perhaps just note in release notes documenting that a field in the dict has changed

I see here: https://capitalone.github.io/DataProfiler/docs/0.10.5/html/dataprofiler.dp_logging.html?highlight=chi#dataprofiler.dp_logging.get_child_logger

```
dataprofiler.profilers.profiler_utils.perform_chi_squared_test_for_homogeneity(categories1: dict, sample_size1: int, categories2: dict, sample_size2: int) → dict[str, int | float | None]

    Perform a Chi Squared test for homogeneity between two groups.

    Parameters

            categories1 (dict) – Categories and respective counts of the first group

            sample_size1 (int) – Number of samples in first group

            categories2 (dict) – Categories and respective counts of the second group

            sample_size2 (int) – Number of samples in second group

    Returns

        Results of the chi squared test
    Return type

        dict

```

the documentation only specifies that we are returning a dict but does not define the dict's keys.

2023-10-27 18:59 UTC, taylorfturner commented on dataprofiler/tests/profilers/test_categorical_column_profile.py
more like [this](https://capitalone.github.io/DataProfiler/docs/0.10.5/html/profiler.html#:~:text=%27t%2Dtest%27,value%22%3A%20float) area of the docs

2023-10-27 20:22 UTC, mainkhan commented on dataprofiler/tests/profilers/test_categorical_column_profile.py
Created a companion documentation PR #1057

2023-10-30 13:48 UTC, taylorfturner commented on dataprofiler/tests/profilers/test_categorical_column_profile.py
awesome

2023-10-30 14:02 UTC, taylorfturner commented on dataprofiler/profilers/numerical_column_stats.py
> +        conservative_t = scipy.stats.t(conservative_deg_of_free)
scipy refers to this as `df`; however, I agree for clarity in this repo a rename would make the code. Its more readable / cause less confusion / less ambiguity  and as a result --> easier to maintain

2023-10-30 14:34 UTC, taylorfturner approved these changes

2023-10-30 14:54 UTC, micdavis approved these changes

2023-10-30 14:54 UTC, merged