Temp
capitalone/DataProfiler pull request #1096
Opened 2024-02-19 19:09 UTC by SchadtJ

Add Unit tests + fill out

2024-02-19 19:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/capitalone/DataProfiler?pullRequest=1096) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/capitalone/DataProfiler?pullRequest=1096) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/capitalone/DataProfiler?pullRequest=1096) it.</sub>

2024-02-21 18:42 UTC, taylorfturner reviewed
Please sign the CLA @SchadtJ. Thanks!

2024-02-21 18:44 UTC, taylorfturner requested changes
PR will also need to go into `dev` branch and not `main` per contribution docs [here](https://github.com/capitalone/dataprofiler/blob/main/.github/CONTRIBUTING.md#creating-pull-requests).

2024-02-23 17:07 UTC, SchadtJ commented on dataprofiler/profilers/float_column_profile.py
> +            .astype(object)
Hey @taylorfturner - thank you for the comments. Signed SLA / will fork off dev in the future. 

I'm planning to close this PR. I had originally intended this to be a fix for [this](https://github.com/capitalone/DataProfiler/issues/1048) issue. However, I believe this [PR](https://github.com/capitalone/DataProfiler/pull/1093) solved the underlying issue.

2024-02-23 17:08 UTC, closed without merging