fix: datetime profile JSON encoding bug
capitalone/DataProfiler pull request #1102
Opened 2024-03-01 15:36 UTC by scottiegarcia

Reopening [this PR](https://github.com/capitalone/DataProfiler/pull/1101) since latest commit wasn't being reflected.

I'm assuming [this PR](https://github.com/capitalone/DataProfiler/pull/1097) was also made to alleviate the bug in the test I addressed. I figure modifying the test behavior is preferable to pinning the version as the bug is introduced within the test

2024-03-01 15:39 UTC, micdavis submitted a review, later dismissed

2024-03-04 12:01 UTC, taylorfturner commented
merge to `dev` @scottiegarcia

2024-03-04 13:19 UTC, ksneab7 submitted a review, later dismissed

2024-03-04 13:20 UTC, ksneab7 commented
Change target branch to dev and I am happy with this :)

2024-03-04 13:37 UTC, taylorfturner requested changes
target to `dev` not `main`

2024-03-04 20:21 UTC, closed without merging