docs: add contributor notes on where to find documentation branches
capitalone/DataProfiler pull request #1113
Opened 2024-03-12 18:38 UTC by carlsonp

2024-03-12 18:42 UTC, taylorfturner requested changes
open into `dev` branch instead of `main` but otherwise LGTM

2024-03-12 18:47 UTC, taylorfturner commented on .github/CONTRIBUTING.md
> +Please see the `gh-pages` and `dev-gh-pages` branches for all documentation.
Technically a PR for updating the documentation should only go into `dev-gh-pages` -- and when we do a release a PR will be opened to `gh-pages`.

2024-03-12 18:48 UTC, taylorfturner approved these changes
LGTM -- small comment for follow-up PR. Thanks for the contribution @carlsonp

2024-03-12 19:55 UTC, taylorfturner requested changes
slightly nuance clarification

2024-03-12 19:55 UTC, taylorfturner commented on .github/CONTRIBUTING.md
> +After you've completed your edits, open a Github Pull Request (PR) to merge into `dev-gh-pages`.  During a version release, `dev-gh-pages` is merged
```suggestion
After you've completed your edits, open a Github Pull Request (PR) to merge into `dev-gh-pages` from your fork.  During a version release, `dev-gh-pages` is merged
```

2024-03-13 17:19 UTC, taylorfturner commented
Seeing a test error: `E   ValueError: Must install dask-expr to activate query planning` probably related to `E   ModuleNotFoundError: No module named 'dask_expr'`. Not seeing this on other PRs at the moment, but dask did make a release yesterday https://pypi.org/project/dask/#history

2024-03-14 13:07 UTC, taylorfturner commented
I approve this change, @carlsonp  -- we'll just need this dask issue resolved so tests pass on the checks. If you have time, welcome to research and propose a fix. Otherwise, I'll have to see if I can get to it later; but this change itself is good! Thanks for the contributions @carlsonp!

2024-03-22 19:50 UTC, taylorfturner commented
@carlsonp you should be good to rebase onto `dev` now

2024-03-24 16:21 UTC, carlsonp commented
Rebased

2024-03-25 12:36 UTC, taylorfturner reviewed
slight update @carlsonp

2024-03-25 12:36 UTC, taylorfturner commented on .github/CONTRIBUTING.md
> +into the `gh-pages` branch and is the version associated with the documentation website and stable version.
```suggestion
into the `gh-pages` branch (after `update_documentation.py` is run) and is the version associated with the documentation website and stable version.
```

2024-03-28 20:15 UTC, taylorfturner approved these changes
LGTM

2024-04-08 16:09 UTC, ksneab7 approved these changes

2024-04-08 16:10 UTC, taylorfturner commented
@carlsonp needs update branch now after #1114  merged

2024-04-08 16:49 UTC, merged