Polars feature updates
capitalone/DataProfiler pull request #1119
Opened 2024-03-22 16:30 UTC by abajpai15

Added polars to datetime_column_profile and unstructured_labeler

2024-04-05 19:53 UTC, taylorfturner commented on dataprofiler/profilers/datetime_column_profile.py
> +        is_row_datetime = pd.Series(np.full((len_df), False))
nice catch

2024-04-05 19:53 UTC, taylorfturner commented on dataprofiler/profilers/unstructured_text_profile.py
> +                )
pre-commit made it like this?

2024-04-05 19:53 UTC, taylorfturner commented on dataprofiler/profilers/unstructured_text_profile.py
> +                )
90% of this is similar ... could make this more modular. follow-up PR maybe or if you can crank it out quick can do this

2024-04-05 19:53 UTC, taylorfturner commented on dataprofiler/profilers/unstructured_text_profile.py
> +        if type(data) is pl.Series:
make this an `isinstance(data, pl.Series)` instead

2024-04-05 19:53 UTC, taylorfturner commented on dataprofiler/profilers/unstructured_text_profile.py
> +        if type(data) is pl.Series:
haven't tested but something like this with `isinstance`

2024-04-05 20:07 UTC, micdavis submitted a review, later dismissed

2024-04-08 12:53 UTC, abajpai15 commented on dataprofiler/profilers/unstructured_text_profile.py
> +                )
Yep

2024-04-08 16:06 UTC, taylorfturner requested changes

2024-04-08 16:06 UTC, taylorfturner commented on dataprofiler/profilers/unstructured_text_profile.py
> +        if type(data) is pl.Series:
let's update this and the `_update_words` prior to merge

2024-04-22 17:12 UTC, taylorfturner approved these changes

2024-04-22 17:57 UTC, ksneab7 approved these changes

2024-04-22 17:58 UTC, merged