Add inplace options in the process function
capitalone/DataProfiler pull request #148
Opened 2021-04-12 16:08 UTC by sagars729

- Add inplace options in CharPostprocessor and StructCharPostprocessor
- Add tests to check that the inplace options works
- https://github.com/capitalone/DataProfiler/issues/91

2021-04-12 17:30 UTC, lettergram requested changes

2021-04-12 17:30 UTC, lettergram commented on dataprofiler/labelers/data_processing.py
>          the original data.
Need to add the parameter description.

2021-04-12 17:30 UTC, lettergram commented on dataprofiler/labelers/data_processing.py
> +    def match_sentence_lengths(data, results, flatten_separator, inplace=True):
Need to add the parameter description.

Kinda weird this function occurs twice

2021-04-12 17:52 UTC, AnhTruong reviewed
agree with Austin. Please add descriptions.

2021-04-12 17:59 UTC, sagars729 commented
@lettergram @AnhTruong added parameter descriptions

2021-04-12 18:43 UTC, ChrisWallace2020 approved these changes

2021-04-13 18:55 UTC, lettergram approved these changes

2021-04-13 18:55 UTC, merged