add example: add new model to data labeler
capitalone/DataProfiler pull request #152
Opened 2021-04-13 20:18 UTC by AnhTruong

address the issue https://github.com/capitalone/DataProfiler/issues/12

2021-04-14 15:12 UTC, lettergram reviewed
I believe there needs to be a more sizable explanation on what's going on here. To me, I just see a wall of text. While I see a model is designed, I would need further assistance to get it to work. I'm not really sure how it fits in the pipeline etc.

Recommendations:

* Reduce the actual code portions where possible
* Expand comment descriptions
* Possibly add some infographics or text explaining the pipeline `step 1` -> `step 2` -> etc

2021-04-15 15:18 UTC, gme5078 requested changes

2021-04-15 15:18 UTC, gme5078 commented on examples/add_new_model_to_data_labeler.ipynb
> +    "params = {'default_label': 'comment'}\n",
Why do we have this and the above part with adding the UNKNOWN? Only one of these should be needed right?

2021-04-15 15:18 UTC, gme5078 commented on examples/add_new_model_to_data_labeler.ipynb
> +    "params = {'default_label': 'comment'}\n",
And can you please add a conclusion at the end?

2021-04-15 15:18 UTC, gme5078 commented on examples/add_new_model_to_data_labeler.ipynb
> +    "model = CharacterLevelLstmModel(labels + ['UNKNOWN']) # extend the labels with the default label 'UNKNOW'\n",
Typo with "UNKNOW"

2021-04-16 21:05 UTC, gme5078 approved these changes

2021-04-17 03:04 UTC, lettergram approved these changes

2021-04-17 03:13 UTC, merged