[WIP] updates to intuitive profiler choice
capitalone/DataProfiler pull request #247
Opened 2021-05-27 22:27 UTC by JGSweets

Updates Profiler to make choices based on if user doesn't specify:
    1. Data Reader dictates
    2.  Structured Profiler:  DataFrame, Series, List
    3. Unstructured Profiler: Text

2021-05-27 22:28 UTC, JGSweets commented on dataprofiler/profilers/profile_builder.py
> +                                   min_true_samples=None):
this was a mismatch with the other classes

2021-05-27 22:30 UTC, JGSweets commented on dataprofiler/profilers/profile_builder.py
> +    def __init__(self, data, samples_per_update=None, min_true_samples=0,
matches existing API

2021-05-28 14:50 UTC, ChrisWallace2020 commented on dataprofiler/tests/profilers/test_profile_builder.py
> +        empty_csv_df = dp.Data(data=data_df, data_type="csv")
Probably should change variable name since `data_df` is no longer an empty df

2021-05-28 14:50 UTC, ChrisWallace2020 commented on dataprofiler/tests/profilers/test_profile_builder.py
> +        empty_csv_rec = dp.Data(data=data_df, data_type="csv",
Same as above

2021-05-28 15:06 UTC, lettergram commented on dataprofiler/profilers/profile_builder.py
> +    _allowed_external_data_types = (list, pd.Series, pd.DataFrame)
Should we allow list? We haven't in the past and I don't think that's really necessary.

2021-05-28 15:06 UTC, lettergram commented on dataprofiler/profilers/profile_builder.py
> +    _allowed_external_data_types = (str, list, pd.Series, pd.DataFrame)
Why is the unstructured profiler taking in data frames?

2021-05-28 15:08 UTC, lettergram requested changes
An UnstructuredProfiler taking in structured data doesn't make sense to me.

2021-05-28 16:20 UTC, AnhTruong approved these changes

2021-05-28 16:28 UTC, JGSweets commented on dataprofiler/profilers/unstructured_text_profile.py
> -            'back', 'hereby', 'your', "didn't", "didnt", 'only', 'may',
pep8

2021-05-28 16:31 UTC, ChrisWallace2020 submitted a review, later dismissed

2021-05-28 16:46 UTC, gme5078 submitted a review, later dismissed

2021-05-28 16:46 UTC, ChrisWallace2020 submitted a review, later dismissed

2021-05-28 16:53 UTC, ChrisWallace2020 approved these changes

2021-05-28 16:53 UTC, gme5078 approved these changes

2021-05-28 17:01 UTC, merged