Add data loader to GraphData class
capitalone/DataProfiler pull request #528
Opened 2022-07-12 14:59 UTC by MisterPNP

The previous GraphData only contained is_match, a function allowing to differentiate between tabular and graph CSV datasets.

This PR adds the functionality of reading/loading the graph data from the input CSV into a NetworkX graph. This graph contains nodes, edges, and possible attributes for both. The use of NetworkX is very useful for downstream profiling of the data due to NetworkX's integrated functions to analyze and pull information from graphs.

2022-07-12 15:52 UTC, JGSweets requested changes
Changes requested from previous closed PR #527 . Will unblock once updated.

2022-07-12 20:09 UTC, JGSweets commented on dataprofiler/data_readers/graph_data.py
> +        self._data = self._format_data_networkx()
Remove from here as this should occur if someone references the data auto. We only want to load the data if we need to load it :)

2022-07-12 20:16 UTC, taylorfturner commented on dataprofiler/data_readers/graph_data.py
> +
@JGSweets need a `_check_and_return_options` specific to Graph Data? `_check_and_return_options` in CSVData would get run when instantiating the class

2022-07-12 20:17 UTC, JGSweets commented on dataprofiler/data_readers/graph_data.py
>      def csv_column_names(cls, file_path, options):
right now this presumes the first row is the header. Some CSVs have comments at the top. We cause use the info from `CSVData.is_match` and options to determine this. (will also need a test, e.g. single graph data file which has comments before the column names start).
to make this more generic we could do:
```python
@classmethod
def csv_column_names(cls, file_path, delimiter, quotechar, header): 
    column_names = []
    if header is None:
        return column_names

    for _ in range(header + 1):
        row = next(csv_reader)
    .
    .
    .
```
csv.reader can be updated to handle quotechar too:
```python
csv_reader = csv.reader(csv_file, delimiter=delimiter, quotechar=quotechar)
```

2022-07-12 20:18 UTC, JGSweets commented on dataprofiler/data_readers/graph_data.py
> +            options.update(column_names = column_names)
nice!

2022-07-12 20:19 UTC, JGSweets commented on dataprofiler/data_readers/graph_data.py
> +        csv_as_list = data_as_pd.values.tolist()
Can we loop through the df?
or can we use:
https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.from_pandas_edgelist.html

2022-07-12 20:22 UTC, JGSweets commented on dataprofiler/tests/data_readers/test_csv_graph_data.py
> +    def test_data_loader_nodes(self):
Maybe we can add the expected result of nodes, edges in the dict within the `setUpClass`?

2022-07-12 20:24 UTC, JGSweets commented on dataprofiler/data_readers/graph_data.py
> +
@taylorfturner It would, but we aren't inheriting `CSVData`

2022-07-13 16:53 UTC, taylorfturner approved these changes

2022-07-13 17:38 UTC, taylorfturner approved these changes

2022-07-13 17:45 UTC, JGSweets approved these changes

2022-07-13 17:48 UTC, merged