Add Makefile to auto setup repo for developers
capitalone/DataProfiler pull request #699
Opened 2022-10-22 21:20 UTC by tonywu315

2022-10-24 12:39 UTC, taylorfturner commented
@tonywu315 add some notes around how to run it in [`contribution.md`](https://github.com/capitalone/dataprofiler/blob/main/.github/CONTRIBUTING.md) file so its clear exactly how it should run. Thx

2022-10-24 13:49 UTC, taylorfturner commented on Makefile
> +	pip3 install -r requirements-dev.txt; \
how does the package itself get installed in this `venv`? should there be a `pip install -r requirements.txt` too?

2022-10-24 15:42 UTC, taylorfturner commented on Makefile
> +	pip3 install -r requirements-dev.txt; \
perf

2022-10-24 17:36 UTC, taylorfturner requested changes
just a couple things

2022-10-24 17:36 UTC, taylorfturner commented on Makefile
> +	pre-commit run
Didn't run for me ... had to update like below and that ran 

```suggestion
	pip install -e .; \
	pre-commit install; \
	pre-commit run; \
```

2022-10-24 17:36 UTC, taylorfturner commented on Makefile
> +venv: requirements.txt requirements-dev.txt requirements-test.txt
```suggestion
setup: requirements.txt requirements-dev.txt requirements-test.txt
```

2022-10-24 17:36 UTC, taylorfturner commented on .github/CONTRIBUTING.md
> +make
```suggestion
make setup
```

2022-10-24 17:37 UTC, taylorfturner requested changes

2022-10-24 17:37 UTC, taylorfturner commented on .github/CONTRIBUTING.md
> +To set up the development environment, run the following commands:
```suggestion
To set up the development environment, run the following commands in the root of the repo:
```

2022-10-25 15:28 UTC, JGSweets commented on Makefile
> +	pre-commit run; \
should we make a section for `make test` and `make formatting`?

2022-10-25 15:35 UTC, taylorfturner requested changes

2022-10-25 15:35 UTC, taylorfturner commented on Makefile
> +	python -m venv venv
```suggestion
	python3 -m venv venv
```

2022-10-25 17:39 UTC, JGSweets commented on Makefile
> +	pre-commit run; \
last line shouldn't have a `\`

2022-10-25 17:39 UTC, JGSweets commented on Makefile
> +	. venv/bin/activate; \
I believe this is bc the last line has `\` and shouldn't end in `&&` or `;`

2022-10-25 17:50 UTC, taylorfturner commented on Makefile
> +	. venv/bin/activate; \
@tonywu315 I would test locally this rec from @JGSweets ... I tested it one way but didn't work on my end

2022-10-26 13:19 UTC, tonywu315 commented on Makefile
> +	. venv/bin/activate; \
It works for me if I remove the `\` on the last line.

2022-10-26 14:42 UTC, JGSweets commented on Makefile
> +	pre-commit run
Since this is for dev, I believe we need to include the `requirements-reports.txt` and `requirements-ml.txt` for the install as well.

2022-10-26 14:42 UTC, JGSweets commented on .github/CONTRIBUTING.md
> +
It might be good to also include the other makefile components in readme

2022-10-26 16:57 UTC, micdavis approved these changes

2022-10-26 17:03 UTC, JGSweets approved these changes

2022-10-26 17:04 UTC, merged