Updated setup.cfg with check-manifest
capitalone/DataProfiler pull request #705
Opened 2022-11-02 14:40 UTC by Sanketh7

2022-11-02 14:53 UTC, taylorfturner commented
@Sanketh7 needs an `update branch` on this FYI

2022-11-02 15:00 UTC, taylorfturner requested changes

2022-11-02 15:00 UTC, taylorfturner commented on setup.cfg
> +[check-manifest]
will also need to add `check-manifest` hook in `[.pre-commit-config.yaml](https://github.com/capitalone/DataProfiler/blob/main/.pre-commit-config.yaml)`

2022-11-02 19:28 UTC, taylorfturner commented on MANIFEST.in
> +recursive-include examples *.png
concerned these are included in the installation... they shouldn't be

2022-11-02 19:28 UTC, taylorfturner commented on .pre-commit-config.yaml
> +        'networkx','typing-extensions']
run `check-manifest` on `pre-commit run`

2022-11-02 19:28 UTC, taylorfturner commented on MANIFEST.in
> +recursive-include examples *.png
that is `ipynb`, `md`, and `png`

2022-11-02 19:30 UTC, taylorfturner commented on setup.cfg
> +    resources/__pycache__/__init__.cpython**
had to add these for `check-manifest` to pass

2022-11-02 19:34 UTC, taylorfturner commented on MANIFEST.in
> +recursive-include examples *.png
if I take them out I receive 
```
missing from sdist:
  examples/DL-Flowchart.png
  examples/add_new_model_to_data_labeler.ipynb
  examples/column_name_labeler.ipynb
  examples/data_profiler_demo.ipynb
  examples/data_readers.ipynb
  examples/graph_data_demo.ipynb
  examples/great_expecations/README.md
  examples/great_expecations/ge_expect_column_value_confidence_for_data_label.ipynb
  examples/great_expecations/ge_expect_column_values_vs_profile_min.ipynb
  examples/great_expecations/ge_expect_profile_numeric_columns_diff_in_range.ipynb
  examples/great_expecations/ge_expect_profile_numeric_columns_percent_diff_in_range.ipynb
  examples/intro_data_profiler.ipynb
  examples/labeler.ipynb
  examples/merge_profile_list.ipynb
  examples/popmon_dp_loader_example.ipynb
  examples/regex_labeler_from_scratch/DataLabeler_from_scratch.ipynb
  examples/structured_profilers.ipynb
  examples/unstructured_profilers.ipynb
```
and `check-manifest` recommends adding those 3 lines (15 - 17)

2022-11-02 19:35 UTC, taylorfturner commented on requirements-dev.txt
> +check-manifest>=0.48
adding new dependency of `check-manifest` for `pre-commit`

2022-11-02 19:35 UTC, taylorfturner commented on setup.cfg
> +    resources/__pycache__/__init__.cpython**
that is lines 17 - 21

2022-11-02 19:42 UTC, taylorfturner commented on .pre-commit-config.yaml
> +        'networkx','typing-extensions']
have to add these for `check-manifest` to run in the `pre-commit` environment

2022-11-02 19:53 UTC, taylorfturner commented on .pre-commit-config.yaml
> +        'networkx','typing-extensions']
read [this](https://github.com/pre-commit/pre-commit/issues/730) but was reading a post from the creator of `pre-commit` that using `-r requirements.txt` in the `add_dependencies` is not good practice

2022-11-02 21:54 UTC, JGSweets approved these changes

2022-11-03 11:47 UTC, ksneab7 approved these changes

2022-11-03 11:47 UTC, merged