Great Expectations Examples Fix
capitalone/DataProfiler pull request #726
Opened 2022-11-22 20:01 UTC by micdavis

renamed folder name
fixed readme set up steps for examples

2022-11-22 20:05 UTC, JGSweets approved these changes

2022-11-22 20:05 UTC, JGSweets requested changes

2022-11-22 20:05 UTC, JGSweets commented on examples/great_expectations/README.md
> +pip install -e git+https://github.com/great-expectations/great_expectations.git@develop#egg=capitalone-dataprofiler-expectations\&subdirectory=contrib/capitalone_dataprofiler_expectations/ # install
remove -e

2022-11-22 20:09 UTC, taylorfturner commented on examples/great_expectations/README.md
> +pip install -e git+https://github.com/great-expectations/great_expectations.git@develop#egg=capitalone-dataprofiler-expectations\&subdirectory=contrib/capitalone_dataprofiler_expectations/ # install
will approve once updated

2022-11-22 20:09 UTC, taylorfturner commented on .gitignore
> +examples/great_expectations/great_expectations/
lol good catch!

2022-11-22 20:32 UTC, taylorfturner approved these changes

2022-11-22 20:32 UTC, taylorfturner commented
Great work, @micdavis! ty

2022-11-23 01:35 UTC, tyfarnan approved these changes

2022-11-23 01:36 UTC, merged