Forking workflow directions CONTRIBUTING.md
capitalone/DataProfiler pull request #857
Opened 2023-06-05 18:54 UTC by taylorfturner

2023-06-05 20:07 UTC, taylorfturner commented
WIP to add image of branching process and viz of merging

2023-06-06 14:39 UTC, tyfarnan approved these changes

2023-06-06 14:55 UTC, micdavis requested changes
blocking for now

2023-06-06 15:27 UTC, taylorfturner commented on .github/CONTRIBUTING.md
> +</p>
WIP locally

2023-06-07 18:24 UTC, tyfarnan submitted a review, later dismissed

2023-06-07 21:20 UTC, micdavis commented on .github/CONTRIBUTING.md
> +  - Feature branches on forks and on `capitalone/dataprofiler: `feature/<feature_name>`
```suggestion
  - Feature branches on forks and on `capitalone/dataprofiler`: `feature/<feature_name>`
```

2023-06-07 21:39 UTC, JGSweets approved these changes

2023-06-07 21:42 UTC, micdavis approved these changes

2023-06-07 21:54 UTC, merged