ready datalabeler for deserialization and improvement on serializatio…
capitalone/DataProfiler pull request #879
Opened 2023-06-15 18:17 UTC by ksneab7

…n for datalabeler

2023-06-15 18:18 UTC, ksneab7 commented on dataprofiler/labelers/base_data_labeler.py
> +        return labeler
Changes made due to `_default_model_loc` needing to be set for deserialization process

2023-06-16 13:58 UTC, taylorfturner approved these changes

2023-06-16 21:31 UTC, JGSweets approved these changes

2023-06-16 21:34 UTC, JGSweets requested changes
Just one thing: Missing test for `raise ValueError`

2023-06-20 15:24 UTC, taylorfturner requested changes

2023-06-20 15:24 UTC, taylorfturner commented on dataprofiler/tests/labelers/test_data_labelers.py
> +        self.assertEqual("structured_model", data_labeler._default_model_loc)
let's have an additional test to test `rase ValueError` when `default_model_loc` is `None`

2023-06-20 16:26 UTC, JGSweets approved these changes

2023-06-20 16:28 UTC, taylorfturner approved these changes

2023-06-20 16:32 UTC, micdavis approved these changes

2023-06-20 16:42 UTC, merged