Updated DATAPROFILER_SEED setting in utils.py
capitalone/DataProfiler pull request #926
Opened 2023-06-28 18:36 UTC by jacob-buehler

this should fix issue #916 https://github.com/capitalone/DataProfiler/issues/916

2023-06-28 18:39 UTC, taylorfturner requested changes
we'll want some validation / testing of this in `dataprofiler/tests/test_utils.py`

2023-06-28 18:45 UTC, jacob-buehler commented
> we'll want some validation / testing of this in `dataprofiler/tests/test_utils.py`

OK I can do this

2023-06-30 20:06 UTC, JGSweets commented on dataprofiler/profilers/utils.py
> +            random_list[i] = rng.randint(lower_bound_list[i], data_length)
Is this change needed? Or why was it needed? I'm concerned that looping as well is going to be expensive.

2023-07-03 15:08 UTC, JGSweets commented
@taylorfturner also mentioned also abstracting usage for where this is used in the library.

2023-07-11 14:57 UTC, jacob-buehler commented
I am closing this PR, and am moving all work to rngimpo branch on my personal fork

2023-07-11 14:57 UTC, closed without merging