Changed `publish-python-package.yml` to include only release branches.
capitalone/DataProfiler pull request #965
Opened 2023-07-20 19:11 UTC by clee1152

Currently, `publish-python-package.yml` releases any branch of DataProfiler on creation of the branch. This is undesirable. We want to only release the branches named `release/<version>`. To do this, we edit `publish-python-package.yml`.

2023-07-20 19:39 UTC, taylorfturner requested changes

2023-07-20 19:39 UTC, taylorfturner commented on .github/workflows/publish-python-package.yml
> -    types: [created]
I think we'd want to maintain `created` on here ... just want to add the functionality of a limit of what branch on which the workflow can run

2023-07-21 20:28 UTC, taylorfturner approved these changes

2023-07-24 15:22 UTC, JGSweets approved these changes

2023-07-24 15:22 UTC, merged